name = "REPLChat"
uuid = "52867e31-94ac-45a8-b3a3-3934c44562a7"
authors = ["Arsh Sharma"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
